
version: '3.9'
services:
  api:
    build: .
    container_name: cas-vault-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - JWT_SECRET=SFfgsvxcvdfgdfg334534sdf3fsdf454fs19978vnks66aesdeurhjh67
      - JWT_ISSUER=cas-vault
      - JWT_AUDIENCE=cas-vault
      - JWT_EXPIRE_MIN=60

    command: uvicorn app.main:create_app --factory --host 0.0.0.0 --port 8000 --reload
